# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 272673f2d52d932149e31e568b98b4512a039123d2c43998d378541110c1e78d7914462cf8e7f779526aad100c3ef4949bc273fe435f958fe096e14e4fa8ac32

test:
  secret_key_base: e45fc973199403bba6cf58ecedfaaf902260a3c4d45e6b29357a89c3e3f450fb48f751fed04f1adabd260d0a1ba9969520c1e706f444ef7e5465be9a86d511c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
